sudo: false
language: cpp
compiler:
  - gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
script:
  - gcc --version
  - g++ --version
  - make dashing
  - ./dashing dist bonsai/test/GCF_00*z
  - ./dashing dist -8 bonsai/test/GCF_00*z
  - ls bonsai/test/*.gz > fns.txt
  - cp fns.txt qns.txt
  - ./dashing dist --containment-index -Q qns.txt -F fns.txt
  - ./dashing dist -p4 --containment-index -Q qns.txt -F fns.txt
  - ./dashing dist -p4 --countmin --containment-index -Q qns.txt -F fns.txt
notifications:
    slack: jhu-genomics:BbHYSks7DhOolq80IYf6m9oe
    rooms:
      - jhu-genomics:BbHYSks7DhOolq80IYf6m9oe#libsketch
